name: Linters
on: push

defaults:
  run:
    shell: 'bash'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls -alh packages/davatar-storybook/src/stories
      - uses: actions/setup-node@v2
        with:
          node-version: 16 # Need for npm >=7.7
          cache: 'npm'

      # TODO: Install not all dependencies, but only those required for this workflow
      - run: ls -alh packages/davatar-storybook/src/stories
      - name: Install dependencies
        run: npm ci --workspaces
      - run: ls -alh packages/davatar-storybook/src
      - run: ls -alh packages/davatar-storybook/src/stories
      - run: npm run lint
